#pippo: "tanto"
#pippo:
#- pluto
#- 
#pippo:
  #pluto: valore
  #paperino: 
    #-stellina: valore
#presepe:

name: Action di girola
on:
  push: 
jobs: 
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Ciao, sono una stringa!"
      - run: echo "Bubusettede!"
      - run: python --version
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env