#pippo: "tanto"
#pippo:
#- pluto
#-
#pippo:
  #pluto: valore
  #paperino: 
    #-stellina: valore
#presepe:

name: Action di girola
on:
  push: 
jobs: 
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Ciao, sono una stringa!"
      - run: echo "Bubusettede!"
      - run: python --version
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dicianni
            girola
      - run: ls -la
      - uses: actions/setup-python@v5 # equivalente di venv
        with:
          python-version: '3.11.13'
      - run: python --version
      - run: pip install -r requirements.txt
        working-directory: girola
      - run: pip install joblib
      - run: python addestramento_ml.py
        working-directory: girola
      - uses: actions/upload-artifact@v4
        with: 
          name: best_artifact
          path: girola/log_reg.joblib