#pippo: "tanto"
#pippo:
#- pluto
#-
#pippo:
  #pluto: valore
  #paperino: 
    #-stellina: valore
#presepe:

name: Action di girola
on:
  push: 
jobs: 
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Ciao, sono una stringa!"
      - run: echo "Bubusettede!"
      - run: python --version
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            dicianni
      - run: ls -la
      - uses: actions/setup-python@v5 # equivalente di venv
        with:
          python-version: '3.11.9'
      - run: python --version
      - run: python Smart_Farming_Crop_Yield_2024.csv 
      - run: python Addestramento_ml.py
        working-directory: girola
