#pippo: "tanto"
#pippo:
#- pluto
#-
#pippo:
  #pluto: valore
  #paperino: 
    #-stellina: valore
#presepe:

name: Action di Girola

on:
  push:
    branches: [ main, develop ]  # Specify which branches trigger the workflow
  pull_request:
    branches: [ main ]

jobs:
  ciao:
    runs-on: ubuntu-latest
    
    steps:
      # Initial setup and system info
      - name: Print greeting
        run: echo "Ciao, sono una stringa!"
      
      - name: Print fun message
        run: echo "Bubusettede!"
      
      - name: Check system information
        run: |
          echo "=== System Information ==="
          python --version
          pip --version
          lsb_release -d
          echo "=== Network Configuration ==="
          ifconfig
          echo "=== Current Directory ==="
          pwd
          ls -la
          echo "=== Environment Variables ==="
          env
      
      # Checkout repository (full checkout for data files)
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List files after checkout
        run: ls -la
      
      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'
      
      - name: Verify Python version
        run: python --version
      
      # Install dependencies
      - name: Install requirements
        run: pip install -r requirements.txt
        working-directory: girola
      
      - name: Install additional dependencies
        run: pip install joblib
      
      # Run the main script
      - name: Run training script
        run: python addestramento_ml.py
        working-directory: girola
      
      # Upload artifacts
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: best_artifact
          path: girola/log_reg.joblib